### ISSUE TITLE
[casile setup]: make: rules/casile.mk: No such file or directory

### ISSUE THREAD

**Issue by felipesanches** [sile-typesetter/casile-demos#5]
![Screenshot from 2021-07-15 22-22-26](https://user-images.githubusercontent.com/213676/125877534-0e66e723-59d4-4d94-b1b4-d42d09749778.png)

**Comment by felipesanches** [comment]
Not sure if also relevant, but here's the context in which I'm trying the demos: https://github.com/sile-typesetter/casile/issues/123

**Comment by alerque** [comment]
Thanks for this report. I'm pretty sure this is an issue with your build, not with the demo repo (which I just checked in a clean chroot using CasILE v0.6.0). The files it says are missing (`rules/casile.mk` and `rules/rules.mk`) should be part of the CaSILE install. On Arch Linux for example they get installed as `/usr/share/casile/rules/casile.mk`. For some reason your `casile` command does not know where to find these resource files.

Are you running `casile` installed to your system (e.g. having used `sudo make install`) or are you using it aliased to the Git clone where you built it (e.g. `alias casile=~fsanches/devel/github_felipesanches/casile/casile`)? You *can* do the latter, but if you want to run uninstalled like that you do need to used different config options:

```console
$ ./configure --datarootdir=$(cd ..;pwd) --enable-debug
```

Without this it will assume is is being prepared for install and if you try to run it it will look for data resources on your system instead of relative to itself.

If that isn't your problem let me know and I'll try to figure out what is.

**Comment by felipesanches** [comment]
I'll try to figure it out later. I gotta go sleep now since it is 5:25AM in the place I live :-P

Once I get back to it I'll let you know. Thanks for the help!

**Comment by alerque** [comment]
Looking at this again it definitely looks like you were trying to solve a path problem because CaSILE sources were not installed on the system by moving local project files in your book project. The `casile.mk` file should go at the project root, not in a `rules/` directory. The `rules/casile.mk` file it could not find is the one that should be installed. It really does look like you were running the `casile` binary from a source directory where it was built and it doesn't know where to find the resources relative to your project. It *can* be used like this (I do it all the time for developing CaSILE while testing it on some book project) but you must `./configure --datarootdir=$(cd ..;pwd)` for it to use whatever directory you are building in as the expected location for resources.

Happy to help if there is a remaining problem getting started.
